### ISSUE TITLE
When prop for markers changes I'm getting error: TypeError: e[o] is not a function

### ISSUE THREAD

**Issue by aluramh** [ais-one/vue2-leaflet-tracksymbol#2]
Initial load of this component works correctly, only when the props used for the marker change I get this error:
```
TypeError: t[r] is not a function
    at VueComponent.o.(anonymous function).custom.e.$watch.deep
```

When looking at it more closely, it seems that the error is in `<v-ais>` that the `deep watcher` for `latlng` and `options` . I get these warnings from Vue:

```
vue.esm.js?65d7:479 [Vue warn]: Error in callback for watcher "options": 
"TypeError: t[r] is not a function"

found in

---> <VAis>
       <VMarkerCluster>
         <VGroupBase>
           <VMap>
```

And also

```
vue.esm.js?65d7:479 [Vue warn]: Error in callback for watcher "latlng": 
"TypeError: t[r] is not a function"

found in

---> <VAis>
       <VMarkerCluster>
         <VGroupBase>
           <VMap>
```

Is there a fix that I can implement from solving this? Because my map stopped working because of this. Thanks!

**Comment by glennfix** [comment]
Same error here. Any solution for this yet?

**Comment by caiogranero** [comment]
Same error here, any solution?

**Comment by ais-one** [comment]
Hi I just got back from a long project, will try and see if I can fix this...

**Comment by elielr01** [comment]
Hi guys, I have the same error in here, and I've been trying to solve it in my personal project, but I haven't unfortunately. Any idea?

**Comment by ais-one** [comment]
Hi I am redoing the project at the moment, it is pretty outdated, sorry for the inconvenience, will post update...

**Comment by ais-one** [comment]
Hi, I just updated the packages as at this current version 1.0.9, I am now going to find out if there is a problem...

I will add a button with @click that will call a method to change the position of the marker programatically, is this the way to generate the problem that you are experiencing?

**Comment by ais-one** [comment]
I saw the error message already, the problem was with latlng, I should use latLng because it capitalize first letter and add 'set' as suffix to become setLatLng, which is a method in leaflet to change location.

So now we use lat-lng in component props instead of latlng.

<v-ais :lat-lng="location" :options="options"></v-ais>

example has been updated and checked.

I will leave this open for comment and will close it later if there are no further comments.

**Comment by elielr01** [comment]
Hi! I already checked the change and it's now working at my project! Also, that bug isn't there anymore.

Thanks!

**Comment by ais-one** [comment]
ok, thanks, I will close it soon

**Comment by ais-one** [comment]
fixed
