### ISSUE TITLE
Using with SSR?

### ISSUE THREAD

**Issue by EmmanuelBeziat** [ais-one/vue2-leaflet-tracksymbol#7]
Hi,

I'm having a hard time trying to use this plugin in my app. I'm using [Nuxtjs](https://nuxtjs.org/) with a server-side rendering logic. But it forces me to have a weirdy way to call for leaflet and related plugins, by checking for the browser first. I'm not 100% sure this is related to my error, but this is the best hint I have.

All dependencies are up-to-date.

Here's my template (simplified):
```vue
<template>
	<div class="vue-map-container">
		<no-ssr>
			<l-map ref="map" :zoom="mapZoomLevel" :center="mapPosition">
				<l-tilelayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"></l-tilelayer>
				<v-ais :lat-lng="mapPosition" :options="trackerOptions"></v-ais>
			</l-map>
		</no-ssr>
	</div>
</template>

<script>
/**
 * Leaflet can only be loaded on client side
 */
let V2L = {}
let V2LTracksymbol = {}

if (process.browser) {
	L = require('leaflet')
	V2L = require('vue2-leaflet')
	V2LTracksymbol = require('vue2-leaflet-tracksymbol')
}

export default {
	data () {
		return {
			mapPosition: [42.6991088, 2.8694822],
			mapZoomLevel: 6,
				disableClusteringAtZoom: 13
			},
			trackerOptions: {}
		}
	},

	components: {
		'l-map': V2L.LMap,
		'v-ais': V2LTracksymbol,
		'l-tilelayer': V2L.LTileLayer,
	}
}
</script>
```

And the error (in browser console) I keep running into when opening my app:

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <LAis>
       <LMap>
         <NoSsr>
           <Map> at components\Map.vue
             <Default> at layouts\default.vue
               <Root>
```
I have no big deal with other vue2-leaflet plugins to work, but this one is giving me a hard time.
Any idea of what I missed there? Thanks!

**Comment by EmmanuelBeziat** [comment]
Hi,

Actually I'm just using vue2-leaflet… I was using vue2-leafket-markercluster too, but it won't work either since the last update of vue2-leaflet. But even when it was going well, I couldn't get vue2-leaflet-tracksymbol to work — though I'm sure the issue comes from my misunderstanding of this client/ssr paradygm.

I'm very interested in the project you're starting, as it could be a very good source of knowledge about your way to use Leaflet in nuxt. In any case, [here's my project](https://github.com/EmmanuelBeziat/parkourfinder).

Thanks!

**Comment by ais-one** [comment]
Nice, I am working on a company project in a private repo currently, they just started, but I am going to create a nuxt project just to see what happens

**Comment by EmmanuelBeziat** [comment]
Nice one, might come in Handy. Hope to see more of 'em nuxt components!

**Comment by ais-one** [comment]
almost there somewhat... no errors but things seem wierd....

**create map.js in plugins folder**

```
import Vue from 'vue'
import Vue2Leaflet from 'vue2-leaflet'
import Vue2LeafletTracksymbol from 'vue2-leaflet-tracksymbol'

Vue.component('v-ais', Vue2LeafletTracksymbol)
Vue.component('v-map', Vue2Leaflet.LMap);
Vue.component('v-tilelayer', Vue2Leaflet.LTileLayer);
Vue.component('v-marker', Vue2Leaflet.LMarker);

```

**my nuxt.config.js (see css & plugins)**

```
  head: {
    title: 'nuxt-map',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Nuxt.js project' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ],
    css: [
      {src: "leaflet/dist/leaflet.css", lang: 'css'}
    ],
  },
  plugins: [ { src: '~/plugins/map', ssr: false } ],
```

**finally, map.vue in pages...**

```
<template>
  <div id="app">
    <button @click.prevent="ChangeLocation">Change Location</button>
    <no-ssr>
    <v-map  style="height: 90%" :zoom=13 :center="mapCenter">
      <v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></v-tilelayer>
      <!-- v-marker :lat-lng="location"></v-marker -->
      <v-ais :lat-lng="location" :options="options"></v-ais>
    </v-map>
    </no-ssr>
  </div>
</template>

<script>
export default {
  name: 'app',
  methods: {
    ChangeLocation () {
      this.location= [47.413220, -1.209482]
    }
  },
  data () {
    return {
      mapCenter: [47.413220, -1.219482],
      location: [47.413220, -1.219482],
      options: {
        trackId: 123,
        fill: true,
        fillColor: '#00ffff',
        fillOpacity: 1.0,
        stroke: true,
        color: '#000000',
        opacity: 1.0,
        weight: 1.0,
        speed: 30, // meter per second
        course: 1.0, // radians
        heading: 1.0, // radians
        size: 24,
        defaultSymbol: [0.75, 0, 0.5, 0.3, -0.5, 0.3, -0.25, 0, -0.5, -0.3, 0.5, -0.3],
        data: { name: 'Boat 2', custom: 'other info' }
      }
    }
  }
}
</script>

<style>
</style>

```

**Comment by EmmanuelBeziat** [comment]
What does seem weird to you? I'll try this soon to see if it have any effect on my project.

**Comment by ais-one** [comment]
you see any problems?

**Comment by EmmanuelBeziat** [comment]
Actually, just one: I can't get custom markers to work with it. If I do as I previously did, then tracksymbol returns an error…

What I got is this:

```javascript
if (process.browser) {
	const L = require('leaflet')

	delete L.Icon.Default.prototype._getIconUrl

	// eslint-disable-next-line
	L.Icon.Default.mergeOptions({
		iconRetinaUrl: require('~/assets/img/map/marker-icon-2x.png'),
		iconUrl: require('~/assets/img/map/marker-icon.png'),
		shadowUrl: require('~/assets/img/map/marker-shadow.png')
	})
}
```

If I put it in the map.js in plugin folder, with or without the process.browser condition, it Simply won't work and return a 404 for the images.

But if I put it in my template, markers it works and appear, but then I got this:
```
TypeError: L.TrackSymbol is not a constructor
```

Do you happen to use custom markers in your tests ?

**Comment by ais-one** [comment]
No I did not use custom markers, but U can try and add it in to see what happens...

**Comment by EmmanuelBeziat** [comment]
That's the result of my attempts you see just up there. But I'm going to check out directly with the dev of vue2-leaflet about this one.

Thanks again!
